In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk import FreqDist
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
data=pd.read_csv('amazon_baby.csv')

In [3]:
data

name  \
0                                Planetwise Flannel Wipes   
1                                   Planetwise Wipe Pouch   
2                     Annas Dream Full Quilt with 2 Shams   
3       Stop Pacifier Sucking without tears with Thumb...   
4       Stop Pacifier Sucking without tears with Thumb...   
...                                                   ...   
183526  Baby Teething Necklace for Mom Pretty Donut Sh...   
183527  Baby Teething Necklace for Mom Pretty Donut Sh...   
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)   
183529  Baby Food Freezer Tray - Bacteria Resistant, B...   
183530  Best 2 Pack Baby Car Shade for Kids - Window S...   

                                                   review  rating  
0       These flannel wipes are OK, but in my opinion ...       3  
1       it came early and was not disappointed. i love...       5  
2       Very soft and comfortable and warmer than it l...       5  
3       This is a product well worth the purchase.  I ...       5  
4       All of my kids have cried non-stop when I trie...       5  
...                                                   ...     ...  
183526  Such a great idea! very handy to have and look...       5  
183527  This product rocks!  It is a great blend of fu...       5  
183528  This item looks great and cool for my kids.......       5  
183529  I am extremely happy with this product. I have...       5  
183530  I love this product very mush . I have bought ...       5  

[183531 rows x 3 columns]

In [4]:
data.isnull().sum()

name      318
review    829
rating      0
dtype: int64

In [5]:
data=data.dropna()

In [6]:
data.isnull().sum()

name      0
review    0
rating    0
dtype: int64

In [7]:
len(data)

182384

In [7]:
def sentiment(x):
    if x>=3:
        return 1
    else:
        return 0

In [8]:
data['sentiment']=data['rating'].apply(sentiment)

C:\Users\binnu\AppData\Local\Temp/ipykernel_19772/3971230841.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sentiment']=data['rating'].apply(sentiment)


In [9]:
data

name  \
0                                Planetwise Flannel Wipes   
1                                   Planetwise Wipe Pouch   
2                     Annas Dream Full Quilt with 2 Shams   
3       Stop Pacifier Sucking without tears with Thumb...   
4       Stop Pacifier Sucking without tears with Thumb...   
...                                                   ...   
183526  Baby Teething Necklace for Mom Pretty Donut Sh...   
183527  Baby Teething Necklace for Mom Pretty Donut Sh...   
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)   
183529  Baby Food Freezer Tray - Bacteria Resistant, B...   
183530  Best 2 Pack Baby Car Shade for Kids - Window S...   

                                                   review  rating  sentiment  
0       These flannel wipes are OK, but in my opinion ...       3          1  
1       it came early and was not disappointed. i love...       5          1  
2       Very soft and comfortable and warmer than it l...       5          1  
3       This is a product well worth the purchase.  I ...       5          1  
4       All of my kids have cried non-stop when I trie...       5          1  
...                                                   ...     ...        ...  
183526  Such a great idea! very handy to have and look...       5          1  
183527  This product rocks!  It is a great blend of fu...       5          1  
183528  This item looks great and cool for my kids.......       5          1  
183529  I am extremely happy with this product. I have...       5          1  
183530  I love this product very mush . I have bought ...       5          1  

[182384 rows x 4 columns]

In [10]:
import gensim
review_vector=data['review'].apply(gensim.utils.simple_preprocess)
print(review_vector)

0         [these, flannel, wipes, are, ok, but, in, my, ...
1         [it, came, early, and, was, not, disappointed,...
2         [very, soft, and, comfortable, and, warmer, th...
3         [this, is, product, well, worth, the, purchase...
4         [all, of, my, kids, have, cried, non, stop, wh...
                                ...                        
183526    [such, great, idea, very, handy, to, have, and...
183527    [this, product, rocks, it, is, great, blend, o...
183528    [this, item, looks, great, and, cool, for, my,...
183529    [am, extremely, happy, with, this, product, ha...
183530    [love, this, product, very, mush, have, bought...
Name: review, Length: 182384, dtype: object


### Word2Vec

In [11]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4,
)

In [12]:
model.build_vocab(review_vector, progress_per=1000)

In [13]:
model.train(review_vector, total_examples=model.corpus_count, epochs=model.epochs)

(52201802, 70600435)

In [14]:
model.wv.most_similar("good")

[('decent', 0.8250046968460083),
 ('great', 0.7824597358703613),
 ('nice', 0.7095295190811157),
 ('fantastic', 0.6690548062324524),
 ('excellent', 0.655845582485199),
 ('reasonable', 0.6456263065338135),
 ('poor', 0.6294417381286621),
 ('superb', 0.6275391578674316),
 ('terrific', 0.5920728445053101),
 ('neat', 0.5785536170005798)]

In [15]:
model.wv.get_vector('good')

array([-2.0117874e+00, -2.9596704e-01,  2.7205796e+00,  2.5593543e-01,
       -1.1942635e+00,  1.4040507e+00,  2.2292883e+00,  1.0093366e+00,
        1.4949924e+00, -1.8712589e+00,  1.3260252e+00,  2.3352902e+00,
       -3.0450573e+00,  2.6576692e-02,  3.7250743e+00,  1.5142451e-01,
       -1.3041924e+00, -1.4742160e+00, -1.5812613e+00, -2.2929115e+00,
        1.0931792e+00, -2.2314360e-02, -3.8274521e-01, -8.3203804e-01,
        2.6122208e+00,  4.4107184e+00,  2.9742157e+00, -2.8829989e+00,
       -3.8129526e-01,  5.6504947e-01, -5.1987133e+00, -1.3798981e-02,
       -1.4889456e-01, -1.5330722e+00,  3.9161048e+00,  2.5207779e-01,
        2.1340792e+00, -9.4719660e-01,  2.5963802e+00,  1.5988063e+00,
       -2.3259883e+00,  2.3131645e+00,  1.7670436e+00, -1.4934624e+00,
        2.1775882e+00,  1.4478289e-01, -2.4234192e+00, -2.2400908e+00,
       -1.0209852e+00, -1.0704926e+00, -2.8421912e-01, -1.1016467e+00,
       -2.6688716e+00, -2.3085652e-01, -3.3108251e+00, -2.8807466e+00,
      

### Feature vector

In [17]:
keys=model.wv.index_to_key

In [18]:
# Transfrom the training data into feature vectors

def makeFeatureVec(review, model, num_features):
    '''
    Transform a review to a feature vector by averaging feature vectors of words 
    appeared in that review and in the volcabulary list created
    '''
    featureVec = np.zeros((num_features,),dtype="float32")
    nwords = 0.
    index2word_set = set(keys) #key is the volcabulary list of the Word2Vec model
    isZeroVec = True
    review=list(review.split())
    for word in review:
        if word in index2word_set: 
            nwords = nwords + 1.
            featureVec = np.add(featureVec,model.wv.get_vector(word))
            isZeroVec = False
    if isZeroVec == False:
        featureVec = np.divide(featureVec, nwords)
    return featureVec


def getAvgFeatureVecs(reviews, model, num_features):
    '''
    Transform all reviews to feature vectors using makeFeatureVec()
    '''
    counter = 0
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")
    for review in reviews:
        reviewFeatureVecs[counter] = makeFeatureVec(review, model,num_features)
        counter = counter + 1
    return reviewFeatureVecs

In [19]:
X_train, X_test, y_train, y_test = train_test_split(data['review'], data['sentiment'],
                                                    test_size=0.2, random_state=0)
# Get feature vectors for training set
num_features = 100
trainVector = getAvgFeatureVecs(X_train, model, num_features)
print("Training set : %d feature vectors with %d dimensions" %trainVector.shape)


# Get feature vectors for validat
testVector = getAvgFeatureVecs(X_test, model, num_features)
print("Validation set : %d feature vectors with %d dimensions" %testVector.shape)

Training set : 145907 feature vectors with 100 dimensions
Validation set : 36477 feature vectors with 100 dimensions


In [20]:
trainVector

array([[-0.0249407 ,  0.23216245, -0.8775335 , ...,  0.4884561 ,
        -0.9277951 , -0.97064257],
       [-1.0078005 ,  0.56535304,  0.46996042, ...,  0.58479595,
        -0.88835806,  0.4380299 ],
       [ 0.1623176 ,  0.08938474,  0.44997248, ...,  0.6730878 ,
        -0.5746228 , -0.18311878],
       ...,
       [ 0.85366553, -0.2965783 ,  0.1562192 , ...,  0.54886264,
         0.39000088, -0.29044867],
       [ 0.07198919,  0.7802943 ,  0.8511414 , ...,  0.61406165,
        -0.4474815 ,  0.38954905],
       [ 0.6480639 ,  0.07972667,  0.49908933, ...,  0.07833268,
        -0.5837794 ,  0.56441474]], dtype=float32)

### Logistic Regression

In [84]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, accuracy_score, confusion_matrix 

In [22]:
scaler = StandardScaler()
lr = LogisticRegression()
model1 = Pipeline([('standardize', scaler),
                    ('log_reg', lr)])
model1.fit(trainVector, y_train)

Pipeline(steps=[('standardize', StandardScaler()),
                ('log_reg', LogisticRegression())])

In [23]:
y_pred = model1.predict(testVector)

accuracy = accuracy_score(y_test, y_pred)*100
print(accuracy)

print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))

88.04177975162432
Confusion matrix:
 [[ 1857  3439]
 [  923 30258]]


In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.35      0.46      5296
           1       0.90      0.97      0.93     31181

    accuracy                           0.88     36477
   macro avg       0.78      0.66      0.70     36477
weighted avg       0.86      0.88      0.86     36477



### Results

#### Prediction 1

In [31]:
review=X_train[0]
print(review)

These flannel wipes are OK, but in my opinion not worth keeping.  I also ordered someImse Vimse Cloth Wipes-Ocean Blue-12 countwhich are larger, had a nicer, softer texture and just seemed higher quality.  I use cloth wipes for hands and faces and have been usingThirsties 6 Pack Fab Wipes, Boyfor about 8 months now and need to replace them because they are starting to get rough and have had stink issues for a while that stripping no longer handles.


In [35]:
model1.predict(trainVector[0].reshape(1, -1))

array([1], dtype=int64)

In [36]:
y_train[0]

1

#### Prediction 2

In [81]:
review=X_train[100906]
print(review)

I purchased this item after reading so many great reviews, but it just didn\'t work for me with my son. I tried it on a number of different occasions but it was never very effective so I went back to the bulb syringe and had a lot more success. I\'m glad it works so well for some people, I just wasn\'t one of them!


In [82]:
model1.predict(trainVector[100906].reshape(1, -1))

array([0], dtype=int64)

In [83]:
y_train[100906]

0

## The end